include ../Makefile.defines.linux
OBJ=testMyDateTime.o 

testMyDateTime: $(OBJ)
	$(LINKEXE) -o testMyDateTime $(OBJ) $(LDFLAGS) $(LDFLAGSEX)
$(OBJ): testMyDateTime.cpp 
	$(COMPILE) testMyDateTime.cpp
.PHONY:clean
clean:
	rm testMyDateTime $(OBJ)