include ../Makefile.defines.linux

testMyLua: Test.o testLua.o testMyLua.o
	$(LINKEXE) -o testMyLua Test.o TestLua.o testMyLua.o
Test.o: Test.cpp
	$(COMPILE) Test.cpp
TestLua.o: TestLua.cpp
	$(COMPILE) TestLua.cpp
testMyLua.o: testMyLua.cpp 
	$(COMPILE) testMyLua.cpp
lua:
	tolua++ -o TestLua.cpp Test.pkg
.PHONY:clean
clean:
	rm testMyLua $(OBJ)