# config.make generated by configure script
POCO_CONFIG = Linux
POCO_BASE = /home/chenhuidong/poco-1.6.1-all
POCO_BUILD = /home/chenhuidong/poco-1.6.1-all
POCO_PREFIX = /usr/local
POCO_FLAGS = 
OMIT = 
LINKMODE = SHARED
export POCO_CONFIG
export POCO_BASE
export POCO_BUILD
export POCO_PREFIX
export POCO_FLAGS
export LINKMODE
