main: index.cgi signup.cgi signupback.cgi
index.cgi:
	g++ index.cpp -oindex.cgi
signup.cgi:
	g++ signup.cpp -osignup.cgi
signupback.cgi:
	g++ signupback.cpp -osignupback.cgi
.PHONY:clean
clean:
	rm index.cgi signup.cgi signupback.cgi