CC=g++
COMPILE=$(CC) $(CFLAGS) -c
LINK=$(CC) $(CFLAGS) $(LDDIR) $(LDFLAGS)
CFLAGS=-ansi -Wall
OBJ=testMyConf.o MyConf.o

testMyConf: $(OBJ)
	$(LINK) -o testMyConf $(OBJ) 
testMyConf.o: testMyConf.cpp 
	$(COMPILE) testMyConf.cpp
MyConf.o: MyConf.cpp MyConf.h
	$(COMPILE) MyConf.cpp
.PHONY:clean
clean:
	rm testMyConf $(OBJ)