testmsg:
	g++ TestMsg.cpp -otestmsg -lglog
testmsgcreate:
	g++ TestMsgcreate.cpp -otestmsgcreate -lglog
testmsgsnd:
	g++ TestMsgsnd.cpp -otestmsgsnd -lglog
testmsgrcv:
	g++ TestMsgrcv.cpp -otestmsgrcv -lglog
testmsgrmid:
	g++ TestMsgrmid.cpp -otestmsgrmid -lglog
testmsgrcvid:
	g++ TestMsgrcvid.cpp -otestmsgrcvid -lglog
testmsgserver:
	g++ TestMsgServer.cpp -otestmsgserver -lglog
testmsgclient:
	g++ TestMsgClient.cpp -otestmsgclient -lglog
.PHONY:clean
clean:
	rm test*