include ../Makefile.defines.linux
OBJ=testMyDateTime.o 

testMyDateTime: $(OBJ)
	$(LINK) -o testMyDateTime $(OBJ)
$(OBJ): testMyDateTime.cpp 
	$(COMPILE) testMyDateTime.cpp
.PHONY:clean
clean:
	rm testMyDateTime $(OBJ)