all: Console File File1
Console:
	g++ -oConsole Console.cpp -llog4cpp -lpthread
File:
	g++ -oFile File.cpp -llog4cpp -lpthread
File1:
	g++ -oFile1 File1.cpp -llog4cpp -lpthread
clean:
	rm -rf Console File File1