include ../Makefile.defines.linux

all: testMyServ testMyClt
testMyClt: testMyClt.o
	$(LINKEXE) -o testMyClt testMyClt.o
testMyServ: testMyServ.o
	$(LINKEXE) -o testMyServ testMyServ.o
testMyClt.o: testMyClt.cpp  student.pb.cc
	$(COMPILE) testMyClt.cpp student.pb.cc
testMyServ.o: testMyServ.cpp student.pb.cc
	$(COMPILE) testMyServ.cpp student.pb.cc
.PHONY:clean
clean:
	rm testMyServ testMyClt testMyClt.o testMyServ.o
#protoc --cpp_out=.  student.proto