include ../Makefile.defines.linux

all: testMyServ testMyClt
testMyClt: testMyClt.o
	$(LINKEXE) -o testMyClt testMyClt.o
testMyServ: testMyServ.o
	$(LINKEXE) -o testMyServ testMyServ.o
testMyClt.o: testMyClt.cpp 
	$(COMPILE) testMyClt.cpp
testMyServ.o: testMyServ.cpp 
	$(COMPILE) testMyServ.cpp
.PHONY:clean
clean:
	rm testMyServ testMyClt testMyClt.o testMyServ.o