testftok:
	g++ TestFtok.cpp -otestftok -lglog
testpipe:
	g++ TestPipe.cpp -otestpipe -lglog
testdpipe:
	g++ TestDPipe.cpp -otestdpipe -lglog
testpopen:
	g++ TestPopen.cpp -otestpopen -lglog
testfifo:
	g++ TestFifo.cpp -otestfifo -lglog
testmsg:
	g++ TestMsg.cpp -otestmsg -lglog
testmsgcreate:
	g++ Testmsgcreate.cpp -otestmsgcreate -lglog
.PHONY:clean
clean:
	rm test*
