testftok:
	g++ TestFtok.cpp -otestftok -lglog
testpipe:
	g++ TestPipe.cpp -otestpipe -lglog
testdpipe:
	g++ TestDPipe.cpp -otestdpipe -lglog
testpopen:
	g++ TestPopen.cpp -otestpopen -lglog
testfifo:
	g++ TestFifo.cpp -otestfifo -lglog
testmsg:
	g++ TestMsg.cpp -otestmsg -lglog
testmsgcreate:
	g++ TestMsgcreate.cpp -otestmsgcreate -lglog
testmsgsnd:
	g++ TestMsgsnd.cpp -otestmsgsnd -lglog
testmsgrcv:
	g++ TestMsgrcv.cpp -otestmsgrcv -lglog
testmsgrmid:
	g++ TestMsgrmid.cpp -otestmsgrmid -lglog
testmsgrcvid:
	g++ TestMsgrcvid.cpp -otestmsgrcvid -lglog
.PHONY:clean
clean:
	rm test*
