testftok:
	g++ TestFtok.cpp -otestftok -lglog
testpipe:
	g++ TestPipe.cpp -otestpipe -lglog
testdpipe:
	g++ TestDPipe.cpp -otestdpipe -lglog
testpopen:
	g++ TestPopen.cpp -otestpopen 
.PHONY:clean
clean:
	rm test*
