include ../Makefile.defines.linux
all: main MyFrame
main:
	$(LINKEXE) -o main main.cpp $(LDFLAGS) $(LDFLAGSEX)
MyFrame:
	$(LINKEXE) -o MyFrame MyFrame.cpp MyTask.cpp $(LDFLAGS) $(LDFLAGSEX)
.PHONY:clean
clean:
	rm MyFrame main