include ../Makefile.defines.linux

main:
	$(LINKEXE) -o MyFrame MyFrame.cpp MyTask.cpp $(LDFLAGS) $(LDFLAGSEX)
MyFrame:
	$(LINKEXE) -o MyFrame MyFrame.cpp MyTask.cpp $(LDFLAGS) $(LDFLAGSEX)
.PHONY:clean
clean:
	rm MyFrame main