testshmget:
	g++ shmget.cpp -otestshmget -lglog
testshmrmid:
	g++ shmrmid.cpp -otestshmrmid -lglog
testshmwrite:
	g++ shmwrite.cpp -otestshmwrite -lglog
testshmread:
	g++ shmwrite.cpp -otestshmread -lglog
.PHONY:clean
clean:
	rm test*